services:
  - type: web
    name: micro-journal-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn run:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
